export const USER_STATES = {
  INITIALIZING: "INITIALIZING",
  AWAITING_USER_CREATION: "AWAITING_USER_CREATION",
  AWAITING_USER_SETTINGS: "AWAITING_USER_SETTINGS",
  AWAITING_EXERCISE: "AWAITING_EXERCISE",
  EXERCISING: "EXERCISING"
};
